### ISSUE TITLE
nimble build - fails

### ISSUE THREAD

**Issue by bloggins** [nbaertsch/AutoAppDomainHijack#1]
![auto](https://github.com/nbaertsch/AutoAppDomainHijack/assets/3010137/775290cc-874b-47fa-8522-d25e2c6c956f)

When executing "nimble build" the build fails. Please see attached screenshot.

Any assistance would be appreciated

**Comment by nbaertsch** [comment]
I into this myself, install therapist by itself with nimble. The latest
tag'd release does not build but the head of master branch does.

I'll look into the nimble docs and see if I can specify to install head vs
the latest tag.

**Comment by nbaertsch** [comment]
fixed in commit 543602b
